# .github/workflows/nodejs.yml

name: Node.js CI/CD

on:
  push:
    branches:
      - main  # Trigger on push to main branch
  pull_request:
    branches:
      - main  # Trigger on PR to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]  # You can specify the Node.js versions to test against

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Run start
      run: npm start

    - name: Deploy to Production
      if: github.ref == 'refs/heads/main'  # Only deploy if it's on the main branch
      env:
        NODE_ENV: production
      run: |
        echo "Deploying to production"
        # Add deployment script here, e.g., using SSH, a cloud service CLI, etc.
